---
deployment:
  tasks:
    - export PATH="/opt/cpanel/ea-nodejs20/bin:$PATH"
    - export NODE_ENV=production
    - export LOG="/home/cescoco/deploy.log"

    - echo "=== DEPLOY START $(date)" >> "$LOG"
    - npm ci --omit=dev            2>&1 | tee -a "$LOG"
    - npx prisma generate          2>&1 | tee -a "$LOG"
    - npm run migrate:deploy       2>&1 | tee -a "$LOG" || true
    - npm run build                2>&1 | tee -a "$LOG"
    - mkdir -p tmp && touch tmp/restart.txt
    - echo "=== DEPLOY DONE  $(date)"  >> "$LOG"