---
deployment:
  tasks:
    - export PATH="/opt/cpanel/ea-nodejs20/bin:$PATH"
    - export NODE_ENV=production
    - export LOG="/home/cescoco/deploy.log"

    - echo "=== DEPLOY START $(date)" >> "$LOG"

    - npm ci --omit=dev            2>&1 | tee -a "$LOG"

    - ./node_modules/.bin/prisma --version         2>&1 | tee -a "$LOG"
    - ./node_modules/.bin/prisma generate          2>&1 | tee -a "$LOG"
    - ./node_modules/.bin/prisma migrate deploy    2>&1 | tee -a "$LOG" || true

    - npm run build                2>&1 | tee -a "$LOG"

    - mkdir -p tmp && touch tmp/restart.txt
    - echo "=== DEPLOY DONE  $(date)"  >> "$LOG"
