---
deployment:
  tasks:
    # Pakai node/npm dari nodevenv aplikasi (bukan /opt/cpanel/ea-nodejs..)
    - export NODE="/home/cescoco/nodevenv/repositories/CP-Cesco/20/bin/node"
    - export NPM="/home/cescoco/nodevenv/repositories/CP-Cesco/20/bin/npm"
    - export PATH="/home/cescoco/nodevenv/repositories/CP-Cesco/20/bin:$PATH"
    - export NODE_ENV=production
    - export LOG="/home/cescoco/deploy.log"

    - echo "=== DEPLOY START $(date)" >> "$LOG"
    - $NODE -v 2>&1 | tee -a "$LOG"
    - $NPM -v  2>&1 | tee -a "$LOG"

    # Bersihkan supaya fresh
    - rm -rf node_modules 2>/dev/null || true

    # TIDAK pakai 'ci' karena tidak ada package-lock.json
    # Sertakan devDependencies (Tailwind v4/PostCSS dipakai saat build)
    - $NPM install --include=dev                 2>&1 | tee -a "$LOG"

    # Prisma lokal via node absolut
    - $NODE ./node_modules/.bin/prisma --version 2>&1 | tee -a "$LOG"
    - $NODE ./node_modules/.bin/prisma generate  2>&1 | tee -a "$LOG"
    - $NODE ./node_modules/.bin/prisma migrate deploy 2>&1 | tee -a "$LOG" || true

    # Build Next.js -> akan membuat folder .next/
    - $NPM run build                             2>&1 | tee -a "$LOG"

    # Restart Passenger
    - mkdir -p tmp && touch tmp/restart.txt
    - echo "=== DEPLOY DONE $(date)" >> "$LOG"
