---
deployment:
  tasks:
    - export PATH="/opt/cpanel/ea-nodejs20/bin:$PATH"
    - export NODE_ENV=production
    - npm ci
    - npx prisma generate
    - npm run migrate:deploy || true
    - npm run build
    - mkdir -p tmp
    - touch tmp/restart.txt
